import { motion } from 'framer-motion';
import { useFarm } from '@/context/FarmContext';
import { GlassCard } from '@/components/ui/GlassCard';
import { FileText, Download, Calendar, BarChart2 } from 'lucide-react';
import { Button } from '@/components/ui/Button';

export default function Reports() {
  const { activeFarm } = useFarm();

  const reportTypes = [
    { title: 'Daily Summary', desc: 'Water usage, pH/EC averages, and alerts for today.', icon: Calendar, color: 'text-blue-500', bg: 'bg-blue-500/10' },
    { title: 'Weekly Analysis', desc: 'Crop growth progress and resource consumption trends.', icon: BarChart2, color: 'text-emerald-500', bg: 'bg-emerald-500/10' },
    { title: 'Monthly Audit', desc: 'Comprehensive yield estimates and system health report.', icon: FileText, color: 'text-purple-500', bg: 'bg-purple-500/10' },
  ];

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-extrabold text-[#1B4332] flex items-center gap-2">
            <FileText className="w-6 h-6 text-[#2E7D32]" />
            Farm Reports
          </h1>
          <p className="text-[#5E6E64] text-sm font-semibold">Export data and analytics for {activeFarm.name}</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {reportTypes.map((report, idx) => (
          <motion.div key={idx} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: idx * 0.1 }}>
            <div className={`p-6 h-full flex flex-col border border-[#DDE7D9] rounded-2xl shadow-sm ${idx === 0 ? 'bg-white border-t-4 border-t-[#2E7D32]' : idx === 1 ? 'bg-[#EAF7EA]' : 'bg-[#FFF9F2]'}`}>
              <div className="flex items-start gap-4 mb-4">
                <div className={`p-3 rounded-2xl border ${idx === 0 ? 'bg-[#F0F7FF] text-[#2563EB] border-blue-200/50' : idx === 1 ? 'bg-[#EAF7EA] text-[#2E7D32] border-emerald-200/50' : 'bg-[#FFF5F5] text-[#9333EA] border-purple-200/50'}`}>
                  <report.icon className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-[#1B4332]">{report.title}</h3>
                  <p className="text-sm text-[#5E6E64] font-medium mt-1">{report.desc}</p>
                </div>
              </div>
              
              <div className="mt-auto space-y-3 pt-6">
                <Button className="w-full gap-2 border-[#DDE7D9] text-[#2E7D32] bg-white hover:bg-[#EAF7EA]/30 font-bold cursor-pointer" variant="outline" onClick={() => alert('PDF generation is disabled in demo mode.')}>
                  <Download className="w-4 h-4" />
                  Download PDF
                </Button>
                <Button className="w-full gap-2 border-[#DDE7D9] text-[#2E7D32] bg-white hover:bg-[#EAF7EA]/30 font-bold cursor-pointer" variant="outline" onClick={() => alert('CSV export is disabled in demo mode.')}>
                  <Download className="w-4 h-4" />
                  Export CSV
                </Button>
              </div>
            </div>
          </motion.div>
        ))}
      </div>

      <GlassCard className="p-6 mt-8 border-[#DDE7D9]">
        <h3 className="text-lg font-bold text-[#1B4332] mb-6">Recent Exports</h3>
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead>
              <tr className="border-b border-[#DDE7D9] text-sm text-[#1B4332] font-bold bg-[#EEF6EC]/50">
                <th className="p-3 font-bold">Date</th>
                <th className="p-3 font-bold">Report Type</th>
                <th className="p-3 font-bold">Format</th>
                <th className="p-3 font-bold">Generated By</th>
                <th className="p-3 font-bold text-right">Action</th>
              </tr>
            </thead>
            <tbody className="text-sm">
              {[1, 2, 3].map((i) => (
                <tr key={i} className="border-b border-[#DDE7D9] last:border-0 hover:bg-[#EAF7EA]/35 transition-colors">
                  <td className="p-3 text-[#1B4332] font-semibold">Oct {15 - i}, 2026</td>
                  <td className="p-3 text-[#1B4332] font-bold">Weekly Analysis</td>
                  <td className="p-3">
                    <span className="px-2 py-1 bg-[#FFF5F5] text-[#DC2626] border border-red-200/50 rounded text-xs font-bold">PDF</span>
                  </td>
                  <td className="p-3 text-[#5E6E64] font-semibold">Auto-Scheduler</td>
                  <td className="p-3 text-right">
                    <Button variant="ghost" size="sm" className="h-8 font-bold text-[#2E7D32] hover:bg-[#EAF7EA]/30 cursor-pointer">Download</Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </GlassCard>
    </div>
  );
}
