import { motion } from 'framer-motion';
import { useFarm } from '@/context/FarmContext';
import { GlassCard } from '@/components/ui/GlassCard';
import { FileText, Download, Calendar, BarChart2 } from 'lucide-react';
import { Button } from '@/components/ui/Button';

export default function Reports() {
  const { activeFarm } = useFarm();

  const reportTypes = [
    { title: 'Daily Summary', desc: 'Water usage, pH/EC averages, and alerts for today.', icon: Calendar, color: 'text-blue-500', bg: 'bg-blue-500/10' },
    { title: 'Weekly Analysis', desc: 'Crop growth progress and resource consumption trends.', icon: BarChart2, color: 'text-emerald-500', bg: 'bg-emerald-500/10' },
    { title: 'Monthly Audit', desc: 'Comprehensive yield estimates and system health report.', icon: FileText, color: 'text-purple-500', bg: 'bg-purple-500/10' },
  ];

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-800 dark:text-white flex items-center gap-2">
            <FileText className="w-6 h-6 text-primary" />
            Farm Reports
          </h1>
          <p className="text-slate-500 dark:text-slate-400">Export data and analytics for {activeFarm.name}</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {reportTypes.map((report, idx) => (
          <motion.div key={idx} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: idx * 0.1 }}>
            <GlassCard className="p-6 h-full flex flex-col">
              <div className="flex items-start gap-4 mb-4">
                <div className={`p-3 rounded-2xl ${report.bg}`}>
                  <report.icon className={`w-6 h-6 ${report.color}`} />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-slate-800 dark:text-white">{report.title}</h3>
                  <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">{report.desc}</p>
                </div>
              </div>
              
              <div className="mt-auto space-y-3 pt-6">
                <Button className="w-full gap-2" variant="outline" onClick={() => alert('PDF generation is disabled in demo mode.')}>
                  <Download className="w-4 h-4" />
                  Download PDF
                </Button>
                <Button className="w-full gap-2" variant="outline" onClick={() => alert('CSV export is disabled in demo mode.')}>
                  <Download className="w-4 h-4" />
                  Export CSV
                </Button>
              </div>
            </GlassCard>
          </motion.div>
        ))}
      </div>

      <GlassCard className="p-6 mt-8">
        <h3 className="text-lg font-bold text-slate-800 dark:text-white mb-6">Recent Exports</h3>
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead>
              <tr className="border-b border-slate-200 dark:border-slate-800 text-sm text-slate-500 dark:text-slate-400">
                <th className="pb-3 font-medium">Date</th>
                <th className="pb-3 font-medium">Report Type</th>
                <th className="pb-3 font-medium">Format</th>
                <th className="pb-3 font-medium">Generated By</th>
                <th className="pb-3 font-medium text-right">Action</th>
              </tr>
            </thead>
            <tbody className="text-sm">
              {[1, 2, 3].map((i) => (
                <tr key={i} className="border-b border-slate-100 dark:border-slate-800/50 last:border-0 hover:bg-slate-50 dark:hover:bg-slate-800/30 transition-colors">
                  <td className="py-4 text-slate-800 dark:text-slate-300">Oct {15 - i}, 2026</td>
                  <td className="py-4 text-slate-800 dark:text-slate-300 font-medium">Weekly Analysis</td>
                  <td className="py-4">
                    <span className="px-2 py-1 bg-red-500/10 text-red-500 rounded text-xs font-medium">PDF</span>
                  </td>
                  <td className="py-4 text-slate-500">Auto-Scheduler</td>
                  <td className="py-4 text-right">
                    <Button variant="ghost" size="sm" className="h-8">Download</Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </GlassCard>
    </div>
  );
}
