import { motion } from 'framer-motion';
import { useFarm } from '@/context/FarmContext';
import { GlassCard } from '@/components/ui/GlassCard';
import { FileText, Download, Calendar, Droplets, Zap, Leaf, DollarSign, Activity } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import api from '@/lib/api';

export default function Reports() {
  const { activeFarm } = useFarm();

  if (!activeFarm) return null;

  const reportTypes = [
    { type: 'daily-water', title: 'Daily Water Usage', desc: 'Detailed hourly breakdown of water consumption.', icon: Droplets, color: 'text-blue-500', bg: 'bg-blue-500/10' },
    { type: 'daily-fertilizer', title: 'Daily Fertilizer Usage', desc: 'NPK and micronutrient application logs.', icon: Zap, color: 'text-amber-500', bg: 'bg-amber-500/10' },
    { type: 'monthly', title: 'Monthly Consumption', desc: 'Aggregated resource usage for the month.', icon: Calendar, color: 'text-purple-500', bg: 'bg-purple-500/10' },
    { type: 'yield', title: 'Estimated Yield', desc: 'AI-driven crop yield predictions.', icon: Leaf, color: 'text-emerald-500', bg: 'bg-emerald-500/10' },
    { type: 'cost', title: 'Cost Analysis', desc: 'Financial breakdown of inputs vs expected yield.', icon: DollarSign, color: 'text-rose-500', bg: 'bg-rose-500/10' },
    { type: 'savings', title: 'Water Saving Report', desc: 'Metrics on water saved via AI precision.', icon: Activity, color: 'text-cyan-500', bg: 'bg-cyan-500/10' },
  ];

  const handleDownload = async (type: string, format: string) => {
    try {
      const res = await api.get(`/reports/daily?farmId=${activeFarm?.id}&type=${type}`);
      const dataStr = JSON.stringify(res.data.data, null, 2);
      
      // Simple generic download
      const blob = new Blob([dataStr], { type: format === 'json' ? 'application/json' : 'text/plain' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${activeFarm?.name}_${type}_report.${format}`;
      a.click();
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Error generating report', error);
      alert('Error generating report');
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-foreground flex items-center gap-2">
            <FileText className="w-6 h-6 text-primary" />
            Farm Reports
          </h1>
          <p className="text-muted-foreground">Export data and analytics for {activeFarm.name}</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {reportTypes.map((report, idx) => (
          <motion.div key={idx} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: idx * 0.1 }}>
            <GlassCard className="p-6 h-full flex flex-col">
              <div className="flex items-start gap-4 mb-4">
                <div className={`p-3 rounded-2xl ${report.bg}`}>
                  <report.icon className={`w-6 h-6 ${report.color}`} />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-foreground">{report.title}</h3>
                  <p className="text-sm text-muted-foreground mt-1">{report.desc}</p>
                </div>
              </div>
              
              <div className="mt-auto space-y-3 pt-6">
                <Button className="w-full gap-2" variant="outline" onClick={() => handleDownload(report.type, 'json')}>
                  <Download className="w-4 h-4" />
                  Download JSON
                </Button>
                <Button className="w-full gap-2" variant="outline" onClick={() => handleDownload(report.type, 'csv')}>
                  <Download className="w-4 h-4" />
                  Export CSV (Raw)
                </Button>
              </div>
            </GlassCard>
          </motion.div>
        ))}
      </div>

      <GlassCard className="p-6 mt-8">
        <h3 className="text-lg font-bold text-foreground mb-6">Recent Exports</h3>
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead>
              <tr className="border-b border-border text-sm text-muted-foreground">
                <th className="pb-3 font-medium">Date</th>
                <th className="pb-3 font-medium">Report Type</th>
                <th className="pb-3 font-medium">Format</th>
                <th className="pb-3 font-medium">Generated By</th>
                <th className="pb-3 font-medium text-right">Action</th>
              </tr>
            </thead>
            <tbody className="text-sm">
              {[1, 2, 3].map((i) => (
                <tr key={i} className="border-b border-border last:border-0 hover:bg-muted transition-colors">
                  <td className="py-4 text-foreground">Oct {15 - i}, 2026</td>
                  <td className="py-4 text-foreground font-medium">Weekly Analysis</td>
                  <td className="py-4">
                    <span className="px-2 py-1 bg-red-500/10 text-red-500 rounded text-xs font-medium">PDF</span>
                  </td>
                  <td className="py-4 text-muted-foreground">Auto-Scheduler</td>
                  <td className="py-4 text-right">
                    <Button variant="ghost" size="sm" className="h-8">Download</Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </GlassCard>
    </div>
  );
}
